### ISSUE TITLE
Gas prices are not updated anymore. 

### ISSUE THREAD

**Issue by jeesnl** [gruijter/com.gruijter.powerhour#148]
URGENT

**Comment by gruijter** [comment]
YES

**Comment by jeesnl** [comment]
Thanks in advance!

Op di 3 okt 2023 om 17:24 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
I have too many other priorities at the moment. So will take a while before I can dig into this.

**Comment by jeesnl** [comment]
Ok, can understand that. Hope you can find some time soon. I added the Gas
prise device again but unfortunately the same result. Elektricity prices
works correct.

Regards, Jan

Op do 5 okt 2023 om 11:02 schreef gruijter ***@***.***>

**Comment by PeterKawa** [comment]
Same here, I tried many different bidding zones. Homey v8.2.6 - PbtH v5.7.5.
Thanks in advance, Robin. No hurries!
~Peter

**Comment by gruijter** [comment]
Should be fixed in v 5.8.0
https://homey.app/a/com.gruijter.powerhour/test/

**Comment by jeesnl** [comment]
Issue is back, Gas prices are not updated anymore. 
![IMG_9443](https://github.com/gruijter/com.gruijter.powerhour/assets/39216786/5c4cbaff-25cd-4367-bfb9-8001f46d55f2)
